          ok  Starting native_osx for sync app-sync
          ok  app-sync container still running, restarting unison in container
unison: stopped
unison: started
     success  Sync container started
     success  Showing unison logs from your sync container: app-sync
[2022-05-21 16:54:24 +0800] Sync Log:  tail: can't open '/tmp/unison.log': No such file or directory
    shutdown  Shutting down...
          ok  Stopping sync container app-sync
          ok  Starting native_osx for sync app-sync
          ok  app-sync container still running, restarting unison in container
unison: stopped
unison: started
     success  Sync container started
     success  Showing unison logs from your sync container: app-sync
[2022-06-07 21:47:52 +0800] Sync Log:  tail: can't open '/tmp/unison.log': No such file or directory
          ok  Starting native_osx for sync app-sync
          ok  app-sync container still running, restarting unison in container
unison: stopped
unison: started
     success  Sync container started
     success  Showing unison logs from your sync container: app-sync
    shutdown  Shutting down...
          ok  Stopping sync container app-sync
[2022-06-07 22:12:41 +0800] Sync Log:  tail: can't open '/tmp/unison.log': No such file or directory
Error response from daemon: dial unix /Users/wangxiaobo/Library/Containers/com.docker.docker/Data/docker.raw.sock: connect: connection refused
          ok  Starting native_osx for sync app-sync
          ok  app-sync container still running, restarting unison in container
unison: stopped
unison: started
     success  Sync container started
     success  Showing unison logs from your sync container: app-sync
[2022-06-08 19:44:43 +0800] Sync Log:  tail: can't open '/tmp/unison.log': No such file or directory
          ok  Starting native_osx for sync app-sync
          ok  app-sync container still running, restarting unison in container
unison: stopped
unison: started
     success  Sync container started
     success  Showing unison logs from your sync container: app-sync
